# Generated by Django 5.2.9 on 2025-12-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_application_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='need_fix_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
