# Generated by Django 5.2.9 on 2025-12-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_application_need_fix_at_application_rejected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='review_note',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
