# Generated by Django 5.2.9 on 2025-12-30 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_companyuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appfile',
            name='kind',
            field=models.CharField(choices=[('cv', 'Cv'), ('work', 'Work History'), ('video', 'Video')], max_length=20),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.application')),
            ],
            options={
                'unique_together': {('application', 'event_key')},
            },
        ),
    ]
