# Generated by Django 5.2.9 on 2026-01-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_appfile_kind_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
