# Generated by Django 5.2.9 on 2026-01-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_application_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, choices=[('it', 'IT'), ('restaurant', 'Restaurant'), ('building_cleaning', 'Building Cleaning'), ('hotel_reception', 'Hotel Reception'), ('part_time', 'Part-Time'), ('translator', 'Translator')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='visa_type',
            field=models.CharField(choices=[('work_visa', 'Work Visa'), ('tokuteigino', 'Tokuteigino'), ('tokutei', 'Tokutei'), ('kaigo', 'Kaigo'), ('dependent', 'Dependent'), ('student_visa', 'Student Visa'), ('pr', 'PR')], max_length=50),
        ),
    ]
