# Generated by Django 5.2.9 on 2026-01-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_application_category_alter_application_visa_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='visa_type',
            field=models.CharField(choices=[('work_visa', 'Work Visa'), ('tokuteigino', 'Tokutei Ginou'), ('building_cleaning', 'Building Cleaning'), ('restaurant', 'Restaurant'), ('hotel_reception', 'Hotel Reception'), ('kaigo', 'Kaigo')], max_length=50),
        ),
    ]
